version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- cmd: powershell .\build.ps1 --target=PR
test: off
deploy: off
branches:
  only:
  - dev
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: aab474b807c09fc88e96750671bf4c1612d4b5ee
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true